<?php
/**
 * @file
 * Exceptions when parsing logic trees.
 */

namespace Logic;

/**
 * Exceptions when parsing logic trees.
 * Generated by Tree::parse()
 */
class TreeParseException extends \Exception {
	/**
	 * TreeParseException constructor.
	 * @param string $msg Exception message
	 */
	public function __construct($msg) {
		parent::__construct($msg);
	}
}